#! /bin/bash

# akke houben (2122022)
# poging 1: knip file $1 op in $2 delen
# 

if [ $# -lt 3 ]; then
	echo "useage: slicer1 [filename] [parts] [extention]"
	exit
else
	FILENAME=$1
	EXT=$3
	BASENAME=`basename "${FILENAME}" ${EXT}`
	echo "filename: ${BASENAME}"
	LENGTH=`soxi -D "${FILENAME}"`
	echo "length: ${LENGTH}"
	SLICEL=`echo "scale=10; ${LENGTH}/$2" | bc`
	echo "slice-length: ${SLICEL}"


	DIR=`dirname "${FILENAME}"`/slices
	echo "dir: ${DIR}"
	mkdir "${DIR}"
	
	FILES=`echo "${2}-1" | bc`
	for i in `seq 0 $FILES`  
	do
		START=`echo "scale=10; ${SLICEL}*$i" | bc`
		END=`echo "scale=10; ${SLICEL}*($i+1)" | bc`
		SLICENAME="${DIR}/${BASENAME}_${i}${EXT}"
		echo "slicename: ${SLICENAME}"
		echo "start: ${START}; end: ${END}"

		sox "${FILENAME}" "${SLICENAME}" trim ${START} ${SLICEL}
	done
fi
