#! /bin/bash

# opdracht 2 akke houben 2122022

if [ $# -lt 2 ]; then
	echo "usage: [file extention] [destination extention]"
	exit
else
	IN_TYPE=$1
	OUT_TYPE=$2
	PROMPT=
	while [ -z $PROMPT ] 
	do
		echo -n 'ga door met conversie y/n?'
		read PROMPT
	done
	if [ $PROMPT = 'y' ]; then
		echo "Converting"
	else
		echo "user break"
		exit
	fi
fi

DIR="`pwd`/converted"
echo "${DIR}"

if [ ! -d "${DIR}" ]; then
	mkdir "${DIR}"
fi

for item in *$IN_TYPE 
do
	OUT=`basename "${item}" $1`$2
	TARGET="converted/""${OUT}"	
	echo "converting ${item} to ${TARGET}"
	if [ $2 = ".mp3" ]; then
		lame "${item}" "${TARGET}"	
	else	
		ffmpeg -i "${item}" "${TARGET}" 
	fi
done
