all: telop print_array array_max roteer_array

telop: optellen.cpp
	g++ -c optellen.cpp
	g++ -o telop optellen.cpp 

print_array: print_array.cpp
	g++ -c print_array.cpp
	g++ -o print_array print_array.cpp

array_max: array_max.cpp
	g++ -c array_max.cpp
	g++ -o array_max array_max.cpp

roteer_array: roteer_array.cpp
	g++ -c roteer_array.cpp
	g++ -o roteer_array roteer_array.cpp
